apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - name: svc-a
          image: dakshsawhneyy/demo-service-a:v
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: "http://jaeger-collector.tracing:14268/api/traces"
          - name: SERVICE_B_URI
            value: "http://b-service.app"